# Generated by Django 6.0.3 on 2026-04-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit'), ('BOTH', 'Both')], max_length=5)),
                ('stream_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_threshold', models.FloatField(default=0.85)),
                ('frame_sample_rate', models.IntegerField(default=5)),
                ('input_mode', models.CharField(choices=[('VIDEO_UPLOAD', 'Video Upload'), ('SINGLE_CAMERA', 'Single Camera'), ('DUAL_CAMERA', 'Dual Camera')], default='VIDEO_UPLOAD', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
