# Generated by Django 6.0.3 on 2026-04-02 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('raw_ocr_text', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('status', models.CharField(choices=[('AUTO', 'Auto'), ('PENDING', 'Pending Correction'), ('CORRECTED', 'Corrected'), ('UNREGISTERED', 'Unregistered')], default='AUTO', max_length=15)),
                ('image_path', models.CharField(blank=True, max_length=255)),
                ('camera_id', models.CharField(blank=True, max_length=50)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CorrectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_ocr_text', models.CharField(max_length=20)),
                ('corrected_plate', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='parking.parkinglog')),
            ],
        ),
    ]
