# Generated by Django 6.0.3 on 2026-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinglog',
            name='guest_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='parkinglog',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='raw_ocr_text',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='parkinglog',
            name='status',
            field=models.CharField(choices=[('AUTO', 'Auto'), ('PENDING', 'Pending Correction'), ('CORRECTED', 'Corrected'), ('UNREGISTERED', 'Unregistered'), ('GUEST', 'Guest')], default='AUTO', max_length=15),
        ),
    ]
